### ISSUE TITLE
Request: A combined CRAN version and GitHub version badge

### ISSUE THREAD

**Issue by karthik** [r-hub/cranlogs.app#28]
As discussed on Slack, we are trying to standardize READMEs across the rOpenSci project. In the interest of keeping badges concise and to prevent badge proliferation, we would humbly request a combined CRAN version/status + Github version badge.

Prototype: 
![image](https://user-images.githubusercontent.com/138494/27647929-d2552ae6-5be1-11e7-938f-550e46945b8e.png)

@gaborcsardi mentioned that this would require an entirely new badge. If package is not on CRAN, then badge would reflect that.

Why? This badge would allow a potential user to quickly determine whether a package is on CRAN, and if development on GitHub has progressed considerably more than the last CRAN version. 🙏

**Comment by gaborcsardi** [comment]
Cool. What's the underscore for?

**Comment by karthik** [comment]
Sorry that was a typo.

**Comment by gaborcsardi** [comment]
Do you want to show the number of commits since `0.1`? (Assuming that there is a `0.1` tag in the GH repo.) Sg. like 

![](https://img.shields.io/badge/CRAN%2FGitHub-0.1%2F0.1.9999%2B32-blue.svg)

Or that's too much?

**Comment by sckott** [comment]
i like it

**Comment by karthik** [comment]
I love the idea! I'm not sure if it's possible to add a space before the `+`. I think that it would be great to have a tool tip that says what it means (e.g. 
```
![The GitHub version is 32 commits ahead of the CRAN version](...)
```

**Comment by noamross** [comment]
That's exactly what I was writing, @karthik.  I'm not sure it makes sense without the explanation. Can badges have dynamic tooltips?

**Comment by gaborcsardi** [comment]
I don't think dynamic tooltips are possible on GH, but we can have a generic static one, i.e. `CRAN version / GitHub version + number of commits since last release`.

**Comment by gaborcsardi** [comment]
Here it is with the space:

![](https://img.shields.io/badge/CRAN%2FGitHub-0.1%2F0.1.9999%20%2B32-blue.svg)

**Comment by karthik** [comment]
LGTM @gaborcsardi!

**Comment by gaborcsardi** [comment]
I can also try to put a thin space around the `/` signs, but sizing in an SVG is tricky in general.

**Comment by gaborcsardi** [comment]
Anyway, hopefully next week, after UseR I'll get to it!

**Comment by karthik** [comment]
Bump @gaborcsardi! 🙏

**Comment by pedrohcgs** [comment]
🙏

**Comment by gaborcsardi** [comment]
Yes, sorry. Soon!

**Comment by tanho63** [comment]
shamelessly nudging a great idea! @gaborcsardi

**Comment by gaborcsardi** [comment]
Well, obviously this hasn't happened. 

Unfortunately it is unlikely that it is going to happen, because I don't see a good way of getting the GH versions from GitHub. 

* The GitHub API is rate limited, so that's not great. 
* Getting the `DESCRIPTION` file from the repo is possible, but very slow.
* We could cache it, but then it won't show the latest information.

So I am going to close it. Please open another issue if you have an idea of how this could be implemented.
