### ISSUE TITLE
Why is the downloads count so inflated?

### ISSUE THREAD

**Issue by liuyanguu** [r-hub/cranlogs.app#37]
This is a great package. Thank you. But I really wonder how is it possible that, for example, `ggplot2` is downloaded 1.4M a month as shown on https://cranlogs.r-pkg.org/?
According to [RStudio package manager](https://packagemanager.rstudio.com/client/#/repos/1/packages/ggplot2) the monthly download of `ggplot2` is about 50K. That's about dividing 1.4M by 30 days. 

So actually I am thinking what the count number from cran log mean... because the number returned from each day is about on the 50K level: 
```
cranlogs::cran_downloads("ggplot2", when = "last-month")
```
gives:
```
         date count package
1  2020-11-17 74014 ggplot2
2  2020-11-18 71236 ggplot2
3  2020-11-19 70541 ggplot2
4  2020-11-20 66101 ggplot2
5  2020-11-21 53323 ggplot2
6  2020-11-22 51742 ggplot2
7  2020-11-23 67641 ggplot2
8  2020-11-24 65529 ggplot2
9  2020-11-25 51643 ggplot2
```

**Comment by gaborcsardi** [comment]
cranlogs shows the download counts from the cloud.r-project.org CRAN mirror. These are published at http://cran-logs.rstudio.com/ It is pretty easy to check that they are correct, e.g. for 2020-11-25 like above:

```
❯ wget http://cran-logs.rstudio.com/2020/2020-11-25.csv.gz
--2020-12-18 14:29:51--  http://cran-logs.rstudio.com/2020/2020-11-25.csv.gz
Resolving cran-logs.rstudio.com (cran-logs.rstudio.com)... 52.218.181.226
Connecting to cran-logs.rstudio.com (cran-logs.rstudio.com)|52.218.181.226|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 64161367 (61M) [application/gzip]
Saving to: ‘2020-11-25.csv.gz’

2020-11-25.csv.gz   100%[===================>]  61.19M  9.90MB/s    in 12s

2020-12-18 14:30:04 (4.98 MB/s) - ‘2020-11-25.csv.gz’ saved [64161367/64161367]

❯ zgrep '"ggplot2"' 2020-11-25.csv.gz | wc -l
   51643
```

**Comment by liuyanguu** [comment]
Thank you for your kind reply. I was just raising a question that puzzles me and it is not the problem of your package for sure. I just find the downloading numbers of some packages unbelievably high... Maybe I don't fully understand the meaning of the count. I think it counts more than a simple behaviour that "a user downloads a package".
Thanks anyway!

**Comment by gaborcsardi** [comment]
> I think it counts more than a simple behaviour that "a user downloads a package".

No, it counts exactly that. A user (or automation script, etc.) downloading a package.

**Comment by gaborcsardi** [comment]
Btw. whether these numbers are high or not is relative. E.g. a popular npm package is downloaded about 4 million times a day: https://www.npmjs.com/package/lodash

**Comment by liuyanguu** [comment]
Thank you for your detailed reply. Many thanks!
