### ISSUE TITLE
Download stats appear to not work anymore

### ISSUE THREAD

**Issue by marcusyoung** [r-hub/cranlogs.app#40]
For example:

https://cranlogs.r-pkg.org/badges/grand-total/dplyr
https://cranlogs.r-pkg.org/top/last-day/3

all give a 404

**Comment by laresbernardo** [comment]
This issue is happening again. After checking http://cran-logs.rstudio.com/ I noticed the logs haven't been updated since 2022-11-26 (2 days ago). Maybe we should have an option to fetch data as seen on X date instead of only latest?

**Comment by gaborcsardi** [comment]
For the record, there is a status page at https://status.r-pkg.org/.

**Comment by gaborcsardi** [comment]
> Maybe we should have an option to fetch data as seen on X date instead of only latest?

There is API for that, see the README.
