### ISSUE TITLE
show Badges of  bioconductor packages

### ISSUE THREAD

**Issue by zhilongjia** [r-hub/cranlogs.app#43]
It only supports R packages. could it also show Badges for  Bioconductor packages. Thank you.

**Comment by gaborcsardi** [comment]
We don't have download statistics for Bioconductor packages.

**Comment by zhilongjia** [comment]
how about this "http://bioconductor.org/packages/stats/bioc/DESeq2/DESeq2_stats.tab"?

**Comment by gaborcsardi** [comment]
That's not our data. To serve badges from our DB, we would need daily download data from Bioconductor. Maybe they are willing to serve that or give it to us, but we currently don't have that.
