### ISSUE TITLE
MarkDown badge code to knit to PDF?

### ISSUE THREAD

**Issue by rempsyc** [r-hub/cranlogs.app#44]
When I create a new .Rmd file with simply the CRAN badge, and knit to html, it works:

```r
[![](https://cranlogs.r-pkg.org/badges/rempsyc)](https://cran.r-project.org/package=rempsyc)
```

However, when I attempt to knit to PDF, I get the following error:

```r
! LaTeX Error: File `https://cranlogs.r-pkg.org/badges/rempsyc' not found.

Error: LaTeX failed to compile test-cran.tex. See https://yihui.org/tinytex/r/#debugging for debugging tips. See test-cran.log for more info.
Execution halted
```

Is there any way to make this work for PDF, like automatically converting to an image during the knit? Else is there any way that this could make its way as a feature request, like requesting an image link, like `https://cranlogs.r-pkg.org/badges/rempsyc.jpg`?

**Comment by gaborcsardi** [comment]
You can render the SVG into a PNG if you like, e.g. here is an R solution: https://github.com/ropensci/rsvg

But we are not going to server JPG or PNG badges, they are low quality, and I don't think that there is substantial need for them.

**Comment by rempsyc** [comment]
Thanks! This is actually the ideal solution! For future reference the specific solution is, e.g.,:

````
```{r, include=F}
rsvg::rsvg_png("https://cranlogs.r-pkg.org/badges/grand-total/rempsyc", "rempsyc.png")
```

[![](rempsyc.png)](https://cran.r-project.org/package=rempsyc)
````

And then knitting to PDF is successful.
